import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { useBookmark, useCategories } from '../Hooks';
import { BookComp } from '../components';

const Home: NextPage = () => {
  const { categories } = useCategories();
  const { bookmark } = useBookmark();

  return (
    <div className={styles.container}>
      <Head>
        <title>BukaBuku</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Buka<span className={styles.highlight}>Buku</span>
        </h1>
        <section className={styles.section}>
          <h2>Explore Categories</h2>
          <div className={styles.grid}>
            {
              categories?.map(el =>
                <a href={`/book/${el.id}`} className={styles.card}>
                  {el?.name}
                </a>)
            }
          </div>
        </section>
        <section className={styles.section}>
          <h2>Bookmark</h2>
          {
            !bookmark || bookmark?.length <= 0
              ? <div className={styles.placeholder}>
                <p>No bookmarked</p>
              </div>
              : <div className={styles.gridBook}>
                {
                  bookmark?.map(el =>
                    <BookComp
                      data={el} />
                  )
                }
              </div>
          }
        </section>
      </main>
    </div >
  )
}

export default Home
